font_family JetBrainsMono Nerd Font
font_size 16
# background_opacity 0.7
cursor_trail 1
cursor_trail_decay 0.1 0.6
cursor_trail_start_threshold 2
# cursor_trail_color none

allow_remote_control yes

# color theme generate by pywal16
foreground         #c3c3c7
background         #0f1222
background_opacity 1.0
cursor             #c3c3c7

active_tab_foreground     #0f1222
active_tab_background     #c3c3c7
inactive_tab_foreground   #c3c3c7
inactive_tab_background   #0f1222

active_border_color   #c3c3c7
inactive_border_color #0f1222
bell_border_color     #634C5F

color0       #0f1222
color8       #5e6073
color1       #634C5F
color9       #634C5F
color2       #C0303F
color10      #C0303F
color3       #9B3749
color11      #9B3749
color4       #9C5261
color12      #9C5261
color5       #E55F62
color13      #E55F62
color6       #F99E73
color14      #F99E73
color7       #c3c3c7
color15      #c3c3c7
